import mongoose from "mongoose";
const userSchema = new mongoose.Schema({
    fullName:{
        type:String,
        required:true,
    },
    email:{
        type:String,
        unique:true,
        required:true
    },
    password:{
        type:String,
        required:true,
    },
    profilePic:{
            mediaType:{
                type:String,
            },
            mediaUrl:{
                type:String
            },
            publicId:{
                type:String
                },
    },
    language:{
        type:String,
    },
    isOnboarded:{
        type:Boolean,
        default:false
    },
    state:{
        type:String,
    },
    phoneNumber:{
        type:String,
    },  
    lastLogin:{
        type:Date,
        default:Date.now(),
    },
    Role:{
        type:String,
        enum:["Admin","User"],
        default:"User"
    },
    ResetToken:String,
    ResetTokenExpire:Date,
},{
    timestamps:true
});
export const User = mongoose.model("User",userSchema);